// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      // case TargetPlatform.iOS:
      //   return ios;
      // case TargetPlatform.macOS:
      //   throw UnsupportedError(
      //     'DefaultFirebaseOptions have not been configured for macos - '
      //     'you can reconfigure this by running the FlutterFire CLI again.',
      //   );
      // case TargetPlatform.windows:
      //   throw UnsupportedError(
      //     'DefaultFirebaseOptions have not been configured for windows - '
      //     'you can reconfigure this by running the FlutterFire CLI again.',
      //   );
      // case TargetPlatform.linux:
      //   throw UnsupportedError(
      //     'DefaultFirebaseOptions have not been configured for linux - '
      //     'you can reconfigure this by running the FlutterFire CLI again.',
      //   );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
  apiKey: "AIzaSyAlwQZCbNifBnVgO04CS2KDX0GeG6DhnzU",
  authDomain: "ecommerce-app-1b4de.firebaseapp.com",
  projectId: "ecommerce-app-1b4de",
  storageBucket: "ecommerce-app-1b4de.firebasestorage.app",
  messagingSenderId: "929135264798",
  appId: "1:929135264798:web:0292b1ca9df7cc97985a0f",
  measurementId: "G-XP8LEFZBHD"
      );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlwQZCbNifBnVgO04CS2KDX0GeG6DhnzU',
    appId: '1:929135264798:web:0292b1ca9df7cc97985a0f',
    messagingSenderId: '929135264798',
    projectId: 'ecommerce-app-1b4de',
    storageBucket: 'ecommerce-app-1b4de.firebasestorage.app',
  );

  // static const FirebaseOptions ios = FirebaseOptions(
  //   apiKey: 'AIzaSyDqCVsA1-xlHgNDhtSHpvI4qRM98zVBgOA',
  //   appId: '1:545059185697:ios:45f15c5756e4e9eda9af60',
  //   messagingSenderId: '545059185697',
  //   projectId: 'healthful-dev',
  //   storageBucket: 'healthful-dev.firebasestorage.app',
  //   iosBundleId: 'com.hifah.healthful',
  // );
}

// appId-> ca-app-pub-5403313078782320~4199146521

//banner ad-> ca-app-pub-5403313078782320/3352968710

//Interstitial ad-> ca-app-pub-5403313078782320/2039887047




 